# Generated by Django 5.0 on 2023-12-16 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('other_name', models.CharField(blank=True, max_length=50)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=50)),
                ('date_of_birth', models.DateField(null=True)),
                ('ghana_card_number', models.CharField(blank=True, max_length=15, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Nominal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_bank', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_branch', models.CharField(blank=True, max_length=50, null=True)),
                ('auth_number', models.CharField(blank=True, max_length=50, null=True)),
                ('salary_grade_type', models.CharField(blank=True, max_length=50, null=True)),
                ('salary_grade_level', models.CharField(blank=True, max_length=50, null=True)),
                ('grade_step', models.CharField(blank=True, max_length=50, null=True)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduApp.personal')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_appointment', models.DateField(blank=True, help_text='Enter your date of current appointment', null=True)),
                ('date_at_current_station', models.DateField(blank=True, help_text='Enter your date of current station', null=True)),
                ('ssnit', models.CharField(blank=True, max_length=10, null=True)),
                ('ntc_license_number', models.CharField(blank=True, max_length=10, null=True)),
                ('rank', models.CharField(blank=True, max_length=10, null=True)),
                ('date_promoted_to_rank', models.CharField(blank=True, max_length=10, null=True)),
                ('staff_category', models.CharField(choices=[('Teaching staff', 'Teaching staff'), ('Non teaching staff', 'Non teaching staff')], max_length=20)),
                ('academics', models.CharField(blank=True, max_length=10, null=True)),
                ('professional', models.CharField(blank=True, max_length=10, null=True)),
                ('schedule', models.CharField(blank=True, max_length=10, null=True)),
                ('deaprtment_category', models.CharField(choices=[('Director', 'Director'), ('Human Resource and Development', 'Human Resource and Development'), ('Plannning and Statistics', 'Plannning and Statistics'), ('Finance and Administration', 'Finance and Administration'), ('Teaching and Learning', 'Teaching and Learning')], max_length=50)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EduApp.personal')),
            ],
        ),
    ]
