# Generated by Django 5.0 on 2023-12-16 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='personal',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='EduApp.personal'),
            preserve_default=False,
        ),
    ]
