# Generated by Django 5.0 on 2023-12-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduApp', '0003_personal_user_delete_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='username',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
