# Generated by Django 5.0 on 2023-12-16 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EduApp', '0004_personal_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal',
            old_name='user',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='username',
        ),
    ]
