# Generated by Django 5.0 on 2023-12-17 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduApp', '0007_remove_personal_user_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='user_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EduApp.userprofile'),
        ),
    ]
