# Generated by Django 5.0 on 2023-12-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduApp', '0009_remove_personal_user_profile_personal_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.jpeg', null=True, upload_to=''),
        ),
    ]
