# Generated by Django 4.2.2 on 2023-12-26 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EduApp', '0010_alter_personal_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='deaprtment_category',
            new_name='department_category',
        ),
    ]
