# Generated by Django 4.2.2 on 2023-12-26 22:38

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('EduApp', '0011_rename_deaprtment_category_work_department_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='profile_pic',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=85, scale=None, size=[600, 600], upload_to=''),
        ),
    ]
