# Generated by Django 4.2.2 on 2023-12-28 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduApp', '0012_alter_personal_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nominal',
            name='auth_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nominal',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nominal',
            name='grade_step',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nominal',
            name='name_of_bank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nominal',
            name='salary_grade_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='nominal',
            name='salary_grade_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='academics',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='date_promoted_to_rank',
            field=models.DateField(blank=True, help_text='Enter your date of promotion', null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='professional',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='rank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
