# Generated by Django 4.2.2 on 2023-12-28 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EduApp', '0013_alter_nominal_auth_number_alter_nominal_bank_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='schedule',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
